export const IMAGES = [
    "https://comicsense.b-cdn.net/storage/2024/01/banner.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/beanie-banner-copy.jpg",
    "https://comicsense.b-cdn.net/storage/2023/12/banner-manga.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/tees.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/banner.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/beanie-banner-copy.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/banner.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/beanie-banner-copy.jpg",
    "https://comicsense.b-cdn.net/storage/2023/12/banner-manga.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/tees.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/banner.jpg",
    "https://comicsense.b-cdn.net/storage/2024/01/beanie-banner-copy.jpg",
    "https://comicsense.b-cdn.net/storage/2023/12/banner-manga.jpg",
];
